[[plugin.prepend_fetchers]]
id = "git"
group = "prepend"
url = "*"
run = "git"

[[plugin.prepend_previewers]]
url = "*.csv"
run = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
mime = "application/sqlite3"
run = 'piper -- sqlite3 "$1" ".schema --indent"'
