root = "~/.config"

[include]
# Folders to sync recursively
directories = [
  "fish",
  "nvim",
  "hypr",
  "tmux",
  "alacritty",
  "ghostty",
  "keyd",
  "karabiner",
  "waybar",
  "btop",
  "opencode",
  "aerospace",
]

# Specific files to sync (relative to root, or absolute)
files = ["./chezmoi-sync.toml", "./README.md", "./sync.fish"]

[ignore]
patterns = [
  "nvim/lazy-lock.json",
  "nvim/lua/plugins/theme.lua",
  "nvim/spell",
  "fish/fish_variables",
  "karabiner/automatic_backups",
  "ghostty/mac-overrides",
  "tmux/plugins",
  "waybar/*.bak.*",
  "btop/themes",
  ".DS_Store",
  "opencode/node_modules",
  "opencode/bun.lock",
  "opencode/package.json",
  "opencode/.gitignore",
]
